version: '3.8'

services:
  postgres-db-prod:
    image: postgres:16.2
    container_name: postgres-db-prod
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_prod
    ports:
      - "5433:5432"
    volumes:
      - ./database/tg_prod_29_03_2024.sql:/docker-entrypoint-initdb.d/tg_prod.sql

  tg_bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    depends_on:
      - postgres-db-prod
    env_file:
      - ./config/.env.prod
    command: python main.py