version: '3.8'

services:
  postgres-db-dev:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: postgres-db-dev
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./database/tg_dev_29_03_2024.sql:/docker-entrypoint-initdb.d/tg_dev.sql

  tg_bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    depends_on:
      - postgres-db-dev
    env_file:
      - ./config/.env.dev
    command: python main.py