version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tg_bot_09_03.backup:/docker-entrypoint-initdb.d/tg_bot.backup
    
  tg_bot:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - postgres-db
    command: python main.py