version: '3.8'

services:
  postgres-db-dev:
    image: postgres:latest
    container_name: postgres-db-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_dev
    ports:
      - "5434:5432"
    volumes:
      - ./database/tg_dev_29_03_2024.sql:/docker-entrypoint-initdb.d/tg_dev.sql




  postgres-db-prod:
    image: postgres:latest
    container_name: postgres-db-prod
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_prod
    ports:
      - "5433:5432"
    volumes:
      - ./database/tg_prod_29_03_2024.sql:/docker-entrypoint-initdb.d/tg_prod.sql

  tg_bot:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - postgres-db-dev
      - postgres-db-prod
    command: python main.py